from __future__ import annotations
from typing import Any, Optional, Protocol

from ...types import RunContext, ToolCall, ToolResult


class Hook(Protocol):
    def before_run(self, ctx: RunContext) -> None: ...
    def after_run(self, ctx: RunContext, outcome: Any) -> Any: ...
    def before_model_request(self, ctx: RunContext, request: Any) -> Any: ...
    def after_model_response(self, ctx: RunContext, response: Any) -> Any: ...
    def before_tool_call(self, ctx: RunContext, call: ToolCall) -> ToolCall: ...
    def after_tool_result(self, ctx: RunContext, result: ToolResult) -> ToolResult: ...
    def on_error(self, ctx: RunContext, err: Exception) -> Optional[Any]: ...


class BlockedToolCall(RuntimeError):
    pass
