from __future__ import annotations

import io

from pptx import Presentation


class PptxExporter:
    def mime_type(self) -> str:
        return "application/vnd.openxmlformats-officedocument.presentationml.presentation"

    def filename(self) -> str:
        return "report.pptx"

    def render_bytes(self, *, title: str, outcome: dict) -> bytes:

        prs = Presentation()

        # ---- Title Slide ----
        slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(slide_layout)

        slide.shapes.title.text = title
        slide.placeholders[1].text = "Generated by Deep Research"

        # ---- Summary Slide ----
        slide_layout = prs.slide_layouts[1]
        slide = prs.slides.add_slide(slide_layout)

        slide.shapes.title.text = "Executive Summary"
        slide.placeholders[1].text = str(outcome.get("answer", ""))[:1200]

        # ---- Claims Slides ----
        claims = outcome.get("claims") or []

        for c in claims[:10]:
            slide = prs.slides.add_slide(prs.slide_layouts[1])
            slide.shapes.title.text = "Claim"

            txt = c.get("text") if isinstance(c, dict) else str(c)
            slide.placeholders[1].text = txt[:1200]

        # ---- Save to bytes ----
        buf = io.BytesIO()
        prs.save(buf)
        return buf.getvalue()
