from __future__ import annotations

from typing import Protocol

from agent_ext.todo.models import Task, TaskCreate, TaskPatch, TaskQuery


class TaskStore(Protocol):
    async def create_task(self, data: TaskCreate) -> Task: ...
    async def get_task(self, task_id: str) -> Task | None: ...
    async def list_tasks(self, q: TaskQuery) -> list[Task]: ...
    async def update_task(self, task_id: str, patch: TaskPatch) -> Task | None: ...
    async def delete_task(self, task_id: str) -> bool: ...

    async def add_dependency(self, task_id: str, depends_on_task_id: str) -> Task | None: ...
    async def add_subtask(self, parent_id: str, data: TaskCreate) -> Task: ...

    async def next_runnable_tasks(self, q: TaskQuery) -> list[Task]: ...
    async def refresh_blocked_status(self, q: TaskQuery) -> int: ...

    async def get_task_tree(self, root_task_id: str, include_rollup: bool = False) -> dict | None: ...
