"""Database backend protocol."""

from __future__ import annotations

from typing import Protocol

from .types import DatabaseConfig, QueryResult, SchemaInfo, TableInfo


class DatabaseBackend(Protocol):
    """Protocol for database backends (SQLite, PostgreSQL, etc.)."""

    config: DatabaseConfig

    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def list_tables(self) -> list[TableInfo]: ...
    async def describe_table(self, table_name: str) -> TableInfo: ...
    async def get_schema(self) -> SchemaInfo: ...
    async def execute_query(self, sql: str) -> QueryResult: ...
    async def sample_table(self, table_name: str, limit: int = 5) -> QueryResult: ...
